--------------------------------------------------------
-- Archivo creado  - domingo-abril-30-2023   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Sequence NOTIFICACIONES_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "BOOKS_ADMIN"."NOTIFICACIONES_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 161 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence SOLICITUD_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "BOOKS_ADMIN"."SOLICITUD_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 61 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Table BORRAR
--------------------------------------------------------

  CREATE TABLE "BOOKS_ADMIN"."BORRAR" 
   (	"COLUMN1" NUMBER(*,0), 
	"COLUMN2" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table NOTIFICACIONES
--------------------------------------------------------

  CREATE TABLE "BOOKS_ADMIN"."NOTIFICACIONES" 
   (	"ID_NOTIFICACION" NUMBER(10,0), 
	"FECHA_CREACION" TIMESTAMP (6), 
	"FK_SOLICITUD" NUMBER(10,0)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table SOLICITUD
--------------------------------------------------------

  CREATE TABLE "BOOKS_ADMIN"."SOLICITUD" 
   (	"TYS" NUMBER(10,0), 
	"COLUMN1" VARCHAR2(255 CHAR), 
	"CRON_HOSTNAME" VARCHAR2(255 CHAR), 
	"ESTADO_NOTIFICACION" NUMBER(10,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into BOOKS_ADMIN.BORRAR
SET DEFINE OFF;
REM INSERTING into BOOKS_ADMIN.NOTIFICACIONES
SET DEFINE OFF;
REM INSERTING into BOOKS_ADMIN.SOLICITUD
SET DEFINE OFF;
Insert into BOOKS_ADMIN.SOLICITUD (TYS,COLUMN1,CRON_HOSTNAME,ESTADO_NOTIFICACION) values (1,null,'0510c2b8-ee1a-4337-b21f-e1ddaeb7680b',0);
Insert into BOOKS_ADMIN.SOLICITUD (TYS,COLUMN1,CRON_HOSTNAME,ESTADO_NOTIFICACION) values (2,null,'0510c2b8-ee1a-4337-b21f-e1ddaeb7680b',0);
Insert into BOOKS_ADMIN.SOLICITUD (TYS,COLUMN1,CRON_HOSTNAME,ESTADO_NOTIFICACION) values (3,null,'0510c2b8-ee1a-4337-b21f-e1ddaeb7680b',0);
Insert into BOOKS_ADMIN.SOLICITUD (TYS,COLUMN1,CRON_HOSTNAME,ESTADO_NOTIFICACION) values (4,null,'0510c2b8-ee1a-4337-b21f-e1ddaeb7680b',0);
Insert into BOOKS_ADMIN.SOLICITUD (TYS,COLUMN1,CRON_HOSTNAME,ESTADO_NOTIFICACION) values (5,null,'0510c2b8-ee1a-4337-b21f-e1ddaeb7680b',0);
Insert into BOOKS_ADMIN.SOLICITUD (TYS,COLUMN1,CRON_HOSTNAME,ESTADO_NOTIFICACION) values (6,null,'0510c2b8-ee1a-4337-b21f-e1ddaeb7680b',0);
Insert into BOOKS_ADMIN.SOLICITUD (TYS,COLUMN1,CRON_HOSTNAME,ESTADO_NOTIFICACION) values (7,null,'0510c2b8-ee1a-4337-b21f-e1ddaeb7680b',0);
Insert into BOOKS_ADMIN.SOLICITUD (TYS,COLUMN1,CRON_HOSTNAME,ESTADO_NOTIFICACION) values (8,null,'0510c2b8-ee1a-4337-b21f-e1ddaeb7680b',0);
Insert into BOOKS_ADMIN.SOLICITUD (TYS,COLUMN1,CRON_HOSTNAME,ESTADO_NOTIFICACION) values (9,null,'0510c2b8-ee1a-4337-b21f-e1ddaeb7680b',0);
Insert into BOOKS_ADMIN.SOLICITUD (TYS,COLUMN1,CRON_HOSTNAME,ESTADO_NOTIFICACION) values (10,null,'0510c2b8-ee1a-4337-b21f-e1ddaeb7680b',0);
Insert into BOOKS_ADMIN.SOLICITUD (TYS,COLUMN1,CRON_HOSTNAME,ESTADO_NOTIFICACION) values (11,null,'0510c2b8-ee1a-4337-b21f-e1ddaeb7680b',0);
Insert into BOOKS_ADMIN.SOLICITUD (TYS,COLUMN1,CRON_HOSTNAME,ESTADO_NOTIFICACION) values (12,null,'0510c2b8-ee1a-4337-b21f-e1ddaeb7680b',0);
Insert into BOOKS_ADMIN.SOLICITUD (TYS,COLUMN1,CRON_HOSTNAME,ESTADO_NOTIFICACION) values (13,null,'0510c2b8-ee1a-4337-b21f-e1ddaeb7680b',0);
Insert into BOOKS_ADMIN.SOLICITUD (TYS,COLUMN1,CRON_HOSTNAME,ESTADO_NOTIFICACION) values (14,null,'0510c2b8-ee1a-4337-b21f-e1ddaeb7680b',0);
Insert into BOOKS_ADMIN.SOLICITUD (TYS,COLUMN1,CRON_HOSTNAME,ESTADO_NOTIFICACION) values (15,null,'0510c2b8-ee1a-4337-b21f-e1ddaeb7680b',0);
Insert into BOOKS_ADMIN.SOLICITUD (TYS,COLUMN1,CRON_HOSTNAME,ESTADO_NOTIFICACION) values (16,null,'0510c2b8-ee1a-4337-b21f-e1ddaeb7680b',0);
Insert into BOOKS_ADMIN.SOLICITUD (TYS,COLUMN1,CRON_HOSTNAME,ESTADO_NOTIFICACION) values (17,null,'0510c2b8-ee1a-4337-b21f-e1ddaeb7680b',0);
Insert into BOOKS_ADMIN.SOLICITUD (TYS,COLUMN1,CRON_HOSTNAME,ESTADO_NOTIFICACION) values (18,null,'0510c2b8-ee1a-4337-b21f-e1ddaeb7680b',0);
Insert into BOOKS_ADMIN.SOLICITUD (TYS,COLUMN1,CRON_HOSTNAME,ESTADO_NOTIFICACION) values (19,null,'0510c2b8-ee1a-4337-b21f-e1ddaeb7680b',0);
Insert into BOOKS_ADMIN.SOLICITUD (TYS,COLUMN1,CRON_HOSTNAME,ESTADO_NOTIFICACION) values (20,null,'0510c2b8-ee1a-4337-b21f-e1ddaeb7680b',0);
Insert into BOOKS_ADMIN.SOLICITUD (TYS,COLUMN1,CRON_HOSTNAME,ESTADO_NOTIFICACION) values (21,null,'0510c2b8-ee1a-4337-b21f-e1ddaeb7680b',0);
Insert into BOOKS_ADMIN.SOLICITUD (TYS,COLUMN1,CRON_HOSTNAME,ESTADO_NOTIFICACION) values (22,null,'0510c2b8-ee1a-4337-b21f-e1ddaeb7680b',0);
Insert into BOOKS_ADMIN.SOLICITUD (TYS,COLUMN1,CRON_HOSTNAME,ESTADO_NOTIFICACION) values (23,null,'0510c2b8-ee1a-4337-b21f-e1ddaeb7680b',0);
Insert into BOOKS_ADMIN.SOLICITUD (TYS,COLUMN1,CRON_HOSTNAME,ESTADO_NOTIFICACION) values (24,null,'0510c2b8-ee1a-4337-b21f-e1ddaeb7680b',0);
Insert into BOOKS_ADMIN.SOLICITUD (TYS,COLUMN1,CRON_HOSTNAME,ESTADO_NOTIFICACION) values (25,null,'0510c2b8-ee1a-4337-b21f-e1ddaeb7680b',0);
Insert into BOOKS_ADMIN.SOLICITUD (TYS,COLUMN1,CRON_HOSTNAME,ESTADO_NOTIFICACION) values (26,null,'0510c2b8-ee1a-4337-b21f-e1ddaeb7680b',0);
Insert into BOOKS_ADMIN.SOLICITUD (TYS,COLUMN1,CRON_HOSTNAME,ESTADO_NOTIFICACION) values (27,null,'0510c2b8-ee1a-4337-b21f-e1ddaeb7680b',0);
Insert into BOOKS_ADMIN.SOLICITUD (TYS,COLUMN1,CRON_HOSTNAME,ESTADO_NOTIFICACION) values (28,null,'0510c2b8-ee1a-4337-b21f-e1ddaeb7680b',0);
Insert into BOOKS_ADMIN.SOLICITUD (TYS,COLUMN1,CRON_HOSTNAME,ESTADO_NOTIFICACION) values (29,null,'0510c2b8-ee1a-4337-b21f-e1ddaeb7680b',0);
Insert into BOOKS_ADMIN.SOLICITUD (TYS,COLUMN1,CRON_HOSTNAME,ESTADO_NOTIFICACION) values (30,null,'0510c2b8-ee1a-4337-b21f-e1ddaeb7680b',0);
Insert into BOOKS_ADMIN.SOLICITUD (TYS,COLUMN1,CRON_HOSTNAME,ESTADO_NOTIFICACION) values (31,null,'0510c2b8-ee1a-4337-b21f-e1ddaeb7680b',0);
Insert into BOOKS_ADMIN.SOLICITUD (TYS,COLUMN1,CRON_HOSTNAME,ESTADO_NOTIFICACION) values (32,null,'0510c2b8-ee1a-4337-b21f-e1ddaeb7680b',0);
Insert into BOOKS_ADMIN.SOLICITUD (TYS,COLUMN1,CRON_HOSTNAME,ESTADO_NOTIFICACION) values (33,null,'0510c2b8-ee1a-4337-b21f-e1ddaeb7680b',0);
Insert into BOOKS_ADMIN.SOLICITUD (TYS,COLUMN1,CRON_HOSTNAME,ESTADO_NOTIFICACION) values (34,null,'0510c2b8-ee1a-4337-b21f-e1ddaeb7680b',0);
Insert into BOOKS_ADMIN.SOLICITUD (TYS,COLUMN1,CRON_HOSTNAME,ESTADO_NOTIFICACION) values (35,null,'0510c2b8-ee1a-4337-b21f-e1ddaeb7680b',0);
Insert into BOOKS_ADMIN.SOLICITUD (TYS,COLUMN1,CRON_HOSTNAME,ESTADO_NOTIFICACION) values (36,null,'0510c2b8-ee1a-4337-b21f-e1ddaeb7680b',0);
Insert into BOOKS_ADMIN.SOLICITUD (TYS,COLUMN1,CRON_HOSTNAME,ESTADO_NOTIFICACION) values (37,null,'0510c2b8-ee1a-4337-b21f-e1ddaeb7680b',0);
Insert into BOOKS_ADMIN.SOLICITUD (TYS,COLUMN1,CRON_HOSTNAME,ESTADO_NOTIFICACION) values (38,null,'0510c2b8-ee1a-4337-b21f-e1ddaeb7680b',0);
Insert into BOOKS_ADMIN.SOLICITUD (TYS,COLUMN1,CRON_HOSTNAME,ESTADO_NOTIFICACION) values (39,null,'0510c2b8-ee1a-4337-b21f-e1ddaeb7680b',0);
Insert into BOOKS_ADMIN.SOLICITUD (TYS,COLUMN1,CRON_HOSTNAME,ESTADO_NOTIFICACION) values (40,null,'0510c2b8-ee1a-4337-b21f-e1ddaeb7680b',0);
Insert into BOOKS_ADMIN.SOLICITUD (TYS,COLUMN1,CRON_HOSTNAME,ESTADO_NOTIFICACION) values (41,null,'0510c2b8-ee1a-4337-b21f-e1ddaeb7680b',0);
Insert into BOOKS_ADMIN.SOLICITUD (TYS,COLUMN1,CRON_HOSTNAME,ESTADO_NOTIFICACION) values (42,null,'0510c2b8-ee1a-4337-b21f-e1ddaeb7680b',0);
Insert into BOOKS_ADMIN.SOLICITUD (TYS,COLUMN1,CRON_HOSTNAME,ESTADO_NOTIFICACION) values (43,null,'0510c2b8-ee1a-4337-b21f-e1ddaeb7680b',0);
Insert into BOOKS_ADMIN.SOLICITUD (TYS,COLUMN1,CRON_HOSTNAME,ESTADO_NOTIFICACION) values (44,null,'0510c2b8-ee1a-4337-b21f-e1ddaeb7680b',0);
Insert into BOOKS_ADMIN.SOLICITUD (TYS,COLUMN1,CRON_HOSTNAME,ESTADO_NOTIFICACION) values (45,null,'0510c2b8-ee1a-4337-b21f-e1ddaeb7680b',0);
Insert into BOOKS_ADMIN.SOLICITUD (TYS,COLUMN1,CRON_HOSTNAME,ESTADO_NOTIFICACION) values (46,null,'0510c2b8-ee1a-4337-b21f-e1ddaeb7680b',0);
Insert into BOOKS_ADMIN.SOLICITUD (TYS,COLUMN1,CRON_HOSTNAME,ESTADO_NOTIFICACION) values (47,null,'0510c2b8-ee1a-4337-b21f-e1ddaeb7680b',0);
Insert into BOOKS_ADMIN.SOLICITUD (TYS,COLUMN1,CRON_HOSTNAME,ESTADO_NOTIFICACION) values (48,null,'0510c2b8-ee1a-4337-b21f-e1ddaeb7680b',0);
Insert into BOOKS_ADMIN.SOLICITUD (TYS,COLUMN1,CRON_HOSTNAME,ESTADO_NOTIFICACION) values (49,null,'0510c2b8-ee1a-4337-b21f-e1ddaeb7680b',0);
Insert into BOOKS_ADMIN.SOLICITUD (TYS,COLUMN1,CRON_HOSTNAME,ESTADO_NOTIFICACION) values (50,null,'0510c2b8-ee1a-4337-b21f-e1ddaeb7680b',0);
--------------------------------------------------------
--  DDL for Index BORRAR_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "BOOKS_ADMIN"."BORRAR_PK" ON "BOOKS_ADMIN"."BORRAR" ("COLUMN1") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C008328
--------------------------------------------------------

  CREATE UNIQUE INDEX "BOOKS_ADMIN"."SYS_C008328" ON "BOOKS_ADMIN"."NOTIFICACIONES" ("ID_NOTIFICACION") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C008330
--------------------------------------------------------

  CREATE UNIQUE INDEX "BOOKS_ADMIN"."SYS_C008330" ON "BOOKS_ADMIN"."SOLICITUD" ("TYS") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index BORRAR_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "BOOKS_ADMIN"."BORRAR_PK" ON "BOOKS_ADMIN"."BORRAR" ("COLUMN1") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C008328
--------------------------------------------------------

  CREATE UNIQUE INDEX "BOOKS_ADMIN"."SYS_C008328" ON "BOOKS_ADMIN"."NOTIFICACIONES" ("ID_NOTIFICACION") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C008330
--------------------------------------------------------

  CREATE UNIQUE INDEX "BOOKS_ADMIN"."SYS_C008330" ON "BOOKS_ADMIN"."SOLICITUD" ("TYS") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Trigger NOTIFICACIONES_TRG
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TRIGGER "BOOKS_ADMIN"."NOTIFICACIONES_TRG" 
BEFORE INSERT ON NOTIFICACIONES 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID_NOTIFICACION IS NULL THEN
      SELECT NOTIFICACIONES_SEQ.NEXTVAL INTO :NEW.ID_NOTIFICACION FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "BOOKS_ADMIN"."NOTIFICACIONES_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger SOLICITUD_TRG
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TRIGGER "BOOKS_ADMIN"."SOLICITUD_TRG" 
BEFORE INSERT ON SOLICITUD 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.TYS IS NULL THEN
      SELECT SOLICITUD_SEQ.NEXTVAL INTO :NEW.TYS FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "BOOKS_ADMIN"."SOLICITUD_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger NOTIFICACIONES_TRG
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TRIGGER "BOOKS_ADMIN"."NOTIFICACIONES_TRG" 
BEFORE INSERT ON NOTIFICACIONES 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID_NOTIFICACION IS NULL THEN
      SELECT NOTIFICACIONES_SEQ.NEXTVAL INTO :NEW.ID_NOTIFICACION FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "BOOKS_ADMIN"."NOTIFICACIONES_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger SOLICITUD_TRG
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TRIGGER "BOOKS_ADMIN"."SOLICITUD_TRG" 
BEFORE INSERT ON SOLICITUD 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.TYS IS NULL THEN
      SELECT SOLICITUD_SEQ.NEXTVAL INTO :NEW.TYS FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "BOOKS_ADMIN"."SOLICITUD_TRG" ENABLE;
--------------------------------------------------------
--  Constraints for Table BORRAR
--------------------------------------------------------

  ALTER TABLE "BOOKS_ADMIN"."BORRAR" MODIFY ("COLUMN1" NOT NULL ENABLE);
  ALTER TABLE "BOOKS_ADMIN"."BORRAR" ADD CONSTRAINT "BORRAR_PK" PRIMARY KEY ("COLUMN1")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table NOTIFICACIONES
--------------------------------------------------------

  ALTER TABLE "BOOKS_ADMIN"."NOTIFICACIONES" MODIFY ("ID_NOTIFICACION" NOT NULL ENABLE);
  ALTER TABLE "BOOKS_ADMIN"."NOTIFICACIONES" ADD PRIMARY KEY ("ID_NOTIFICACION")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table SOLICITUD
--------------------------------------------------------

  ALTER TABLE "BOOKS_ADMIN"."SOLICITUD" MODIFY ("TYS" NOT NULL ENABLE);
  ALTER TABLE "BOOKS_ADMIN"."SOLICITUD" ADD PRIMARY KEY ("TYS")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
