--------------------------------------------------------
-- Archivo creado  - sábado-abril-29-2023   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table NOTIFICACIONES
--------------------------------------------------------

  CREATE TABLE "BOOKS_ADMIN"."NOTIFICACIONES" 
   (	"ID_NOTIFICACION" NUMBER(10,0), 
	"FECHA_CREACION" TIMESTAMP (6), 
	"FK_SOLICITUD" NUMBER(10,0)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table SOLICITUD
--------------------------------------------------------

  CREATE TABLE "BOOKS_ADMIN"."SOLICITUD" 
   (	"TYS" NUMBER(10,0), 
	"COLUMN1" VARCHAR2(255 CHAR), 
	"CRON_HOSTNAME" VARCHAR2(255 CHAR), 
	"ESTADO_NOTIFICACION" NUMBER(10,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into BOOKS_ADMIN.NOTIFICACIONES
SET DEFINE OFF;
REM INSERTING into BOOKS_ADMIN.SOLICITUD
SET DEFINE OFF;
Insert into BOOKS_ADMIN.SOLICITUD (TYS,COLUMN1,CRON_HOSTNAME,ESTADO_NOTIFICACION) values (1,null,null,0);
Insert into BOOKS_ADMIN.SOLICITUD (TYS,COLUMN1,CRON_HOSTNAME,ESTADO_NOTIFICACION) values (2,null,null,0);
Insert into BOOKS_ADMIN.SOLICITUD (TYS,COLUMN1,CRON_HOSTNAME,ESTADO_NOTIFICACION) values (3,null,null,0);
Insert into BOOKS_ADMIN.SOLICITUD (TYS,COLUMN1,CRON_HOSTNAME,ESTADO_NOTIFICACION) values (4,null,null,0);
Insert into BOOKS_ADMIN.SOLICITUD (TYS,COLUMN1,CRON_HOSTNAME,ESTADO_NOTIFICACION) values (5,null,null,0);
Insert into BOOKS_ADMIN.SOLICITUD (TYS,COLUMN1,CRON_HOSTNAME,ESTADO_NOTIFICACION) values (6,null,null,0);
Insert into BOOKS_ADMIN.SOLICITUD (TYS,COLUMN1,CRON_HOSTNAME,ESTADO_NOTIFICACION) values (7,null,null,0);
Insert into BOOKS_ADMIN.SOLICITUD (TYS,COLUMN1,CRON_HOSTNAME,ESTADO_NOTIFICACION) values (8,null,null,0);
Insert into BOOKS_ADMIN.SOLICITUD (TYS,COLUMN1,CRON_HOSTNAME,ESTADO_NOTIFICACION) values (9,null,null,0);
Insert into BOOKS_ADMIN.SOLICITUD (TYS,COLUMN1,CRON_HOSTNAME,ESTADO_NOTIFICACION) values (10,null,null,0);
Insert into BOOKS_ADMIN.SOLICITUD (TYS,COLUMN1,CRON_HOSTNAME,ESTADO_NOTIFICACION) values (11,null,null,0);
Insert into BOOKS_ADMIN.SOLICITUD (TYS,COLUMN1,CRON_HOSTNAME,ESTADO_NOTIFICACION) values (12,null,null,0);
Insert into BOOKS_ADMIN.SOLICITUD (TYS,COLUMN1,CRON_HOSTNAME,ESTADO_NOTIFICACION) values (13,null,null,0);
Insert into BOOKS_ADMIN.SOLICITUD (TYS,COLUMN1,CRON_HOSTNAME,ESTADO_NOTIFICACION) values (14,null,null,0);
Insert into BOOKS_ADMIN.SOLICITUD (TYS,COLUMN1,CRON_HOSTNAME,ESTADO_NOTIFICACION) values (15,null,null,0);
Insert into BOOKS_ADMIN.SOLICITUD (TYS,COLUMN1,CRON_HOSTNAME,ESTADO_NOTIFICACION) values (16,null,null,0);
Insert into BOOKS_ADMIN.SOLICITUD (TYS,COLUMN1,CRON_HOSTNAME,ESTADO_NOTIFICACION) values (17,null,null,0);
Insert into BOOKS_ADMIN.SOLICITUD (TYS,COLUMN1,CRON_HOSTNAME,ESTADO_NOTIFICACION) values (18,null,null,0);
Insert into BOOKS_ADMIN.SOLICITUD (TYS,COLUMN1,CRON_HOSTNAME,ESTADO_NOTIFICACION) values (19,null,null,0);
Insert into BOOKS_ADMIN.SOLICITUD (TYS,COLUMN1,CRON_HOSTNAME,ESTADO_NOTIFICACION) values (20,null,null,0);
Insert into BOOKS_ADMIN.SOLICITUD (TYS,COLUMN1,CRON_HOSTNAME,ESTADO_NOTIFICACION) values (21,null,null,0);
Insert into BOOKS_ADMIN.SOLICITUD (TYS,COLUMN1,CRON_HOSTNAME,ESTADO_NOTIFICACION) values (22,null,null,0);
Insert into BOOKS_ADMIN.SOLICITUD (TYS,COLUMN1,CRON_HOSTNAME,ESTADO_NOTIFICACION) values (23,null,null,0);
Insert into BOOKS_ADMIN.SOLICITUD (TYS,COLUMN1,CRON_HOSTNAME,ESTADO_NOTIFICACION) values (24,null,null,0);
Insert into BOOKS_ADMIN.SOLICITUD (TYS,COLUMN1,CRON_HOSTNAME,ESTADO_NOTIFICACION) values (25,null,null,0);
Insert into BOOKS_ADMIN.SOLICITUD (TYS,COLUMN1,CRON_HOSTNAME,ESTADO_NOTIFICACION) values (26,null,null,0);
Insert into BOOKS_ADMIN.SOLICITUD (TYS,COLUMN1,CRON_HOSTNAME,ESTADO_NOTIFICACION) values (27,null,null,0);
Insert into BOOKS_ADMIN.SOLICITUD (TYS,COLUMN1,CRON_HOSTNAME,ESTADO_NOTIFICACION) values (28,null,null,0);
Insert into BOOKS_ADMIN.SOLICITUD (TYS,COLUMN1,CRON_HOSTNAME,ESTADO_NOTIFICACION) values (29,null,null,0);
Insert into BOOKS_ADMIN.SOLICITUD (TYS,COLUMN1,CRON_HOSTNAME,ESTADO_NOTIFICACION) values (30,null,null,0);
Insert into BOOKS_ADMIN.SOLICITUD (TYS,COLUMN1,CRON_HOSTNAME,ESTADO_NOTIFICACION) values (31,null,null,0);
Insert into BOOKS_ADMIN.SOLICITUD (TYS,COLUMN1,CRON_HOSTNAME,ESTADO_NOTIFICACION) values (32,null,null,0);
Insert into BOOKS_ADMIN.SOLICITUD (TYS,COLUMN1,CRON_HOSTNAME,ESTADO_NOTIFICACION) values (33,null,null,0);
Insert into BOOKS_ADMIN.SOLICITUD (TYS,COLUMN1,CRON_HOSTNAME,ESTADO_NOTIFICACION) values (34,null,null,0);
Insert into BOOKS_ADMIN.SOLICITUD (TYS,COLUMN1,CRON_HOSTNAME,ESTADO_NOTIFICACION) values (35,null,null,0);
Insert into BOOKS_ADMIN.SOLICITUD (TYS,COLUMN1,CRON_HOSTNAME,ESTADO_NOTIFICACION) values (36,null,null,0);
Insert into BOOKS_ADMIN.SOLICITUD (TYS,COLUMN1,CRON_HOSTNAME,ESTADO_NOTIFICACION) values (37,null,null,0);
Insert into BOOKS_ADMIN.SOLICITUD (TYS,COLUMN1,CRON_HOSTNAME,ESTADO_NOTIFICACION) values (38,null,null,0);
Insert into BOOKS_ADMIN.SOLICITUD (TYS,COLUMN1,CRON_HOSTNAME,ESTADO_NOTIFICACION) values (39,null,null,0);
Insert into BOOKS_ADMIN.SOLICITUD (TYS,COLUMN1,CRON_HOSTNAME,ESTADO_NOTIFICACION) values (40,null,null,0);
Insert into BOOKS_ADMIN.SOLICITUD (TYS,COLUMN1,CRON_HOSTNAME,ESTADO_NOTIFICACION) values (41,null,null,0);
Insert into BOOKS_ADMIN.SOLICITUD (TYS,COLUMN1,CRON_HOSTNAME,ESTADO_NOTIFICACION) values (42,null,null,0);
Insert into BOOKS_ADMIN.SOLICITUD (TYS,COLUMN1,CRON_HOSTNAME,ESTADO_NOTIFICACION) values (43,null,null,0);
Insert into BOOKS_ADMIN.SOLICITUD (TYS,COLUMN1,CRON_HOSTNAME,ESTADO_NOTIFICACION) values (44,null,null,0);
Insert into BOOKS_ADMIN.SOLICITUD (TYS,COLUMN1,CRON_HOSTNAME,ESTADO_NOTIFICACION) values (45,null,null,0);
Insert into BOOKS_ADMIN.SOLICITUD (TYS,COLUMN1,CRON_HOSTNAME,ESTADO_NOTIFICACION) values (46,null,null,0);
Insert into BOOKS_ADMIN.SOLICITUD (TYS,COLUMN1,CRON_HOSTNAME,ESTADO_NOTIFICACION) values (47,null,null,0);
Insert into BOOKS_ADMIN.SOLICITUD (TYS,COLUMN1,CRON_HOSTNAME,ESTADO_NOTIFICACION) values (48,null,null,0);
Insert into BOOKS_ADMIN.SOLICITUD (TYS,COLUMN1,CRON_HOSTNAME,ESTADO_NOTIFICACION) values (49,null,null,0);
Insert into BOOKS_ADMIN.SOLICITUD (TYS,COLUMN1,CRON_HOSTNAME,ESTADO_NOTIFICACION) values (50,null,null,0);
--------------------------------------------------------
--  DDL for Index SYS_C008328
--------------------------------------------------------

  CREATE UNIQUE INDEX "BOOKS_ADMIN"."SYS_C008328" ON "BOOKS_ADMIN"."NOTIFICACIONES" ("ID_NOTIFICACION") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C008330
--------------------------------------------------------

  CREATE UNIQUE INDEX "BOOKS_ADMIN"."SYS_C008330" ON "BOOKS_ADMIN"."SOLICITUD" ("TYS") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Trigger SOLICITUD_TRG
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TRIGGER "BOOKS_ADMIN"."SOLICITUD_TRG" 
BEFORE INSERT ON SOLICITUD 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.TYS IS NULL THEN
      SELECT SOLICITUD_SEQ.NEXTVAL INTO :NEW.TYS FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "BOOKS_ADMIN"."SOLICITUD_TRG" ENABLE;
--------------------------------------------------------
--  Constraints for Table NOTIFICACIONES
--------------------------------------------------------

  ALTER TABLE "BOOKS_ADMIN"."NOTIFICACIONES" MODIFY ("ID_NOTIFICACION" NOT NULL ENABLE);
  ALTER TABLE "BOOKS_ADMIN"."NOTIFICACIONES" ADD PRIMARY KEY ("ID_NOTIFICACION")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table SOLICITUD
--------------------------------------------------------

  ALTER TABLE "BOOKS_ADMIN"."SOLICITUD" MODIFY ("TYS" NOT NULL ENABLE);
  ALTER TABLE "BOOKS_ADMIN"."SOLICITUD" ADD PRIMARY KEY ("TYS")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
